import { History } from '../state/history.js';
import { TYPES, classesOf, createCompany, parseShares, formatShares, cellKey, valueAt, resultingValues, totals, findBlocking, syncSteps } from '../state/excel-model.js';

const escapeHtml = value => String(value).replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
export class ExcelEditor {
  constructor({ root, toolbar, getDocument, updateDocument, report }) { this.root=root;this.toolbar=toolbar;this.getDocument=getDocument;this.updateDocument=updateDocument;this.report=report;this.history=new History(getDocument().excel);this.focus={};this.bindToolbar(); }
  get excel() { return this.getDocument().excel; }
  get company() { return this.excel.companies.find(item=>item.id===this.excel.selectedCompanyId); }
  replace(excel, record=true) { if(record)this.history.commit(excel);else this.history.replace(excel);this.updateDocument(excel);this.render(); }
  mutate(change) { const excel=structuredClone(this.excel);change(excel);this.replace(excel); }
  synchronize() { const next=syncSteps(this.excel,this.getDocument().steps);if(JSON.stringify(next)!==JSON.stringify(this.excel))this.replace(next);else this.render(); }
  undo() { const next=syncSteps(this.history.undo(),this.getDocument().steps);this.history.replace(next);this.updateDocument(next);this.render(); }
  redo() { const next=syncSteps(this.history.redo(),this.getDocument().steps);this.history.replace(next);this.updateDocument(next);this.render(); }
  restore(excel) { this.history=new History(excel);this.render(); }
  bindToolbar() { this.toolbar.addEventListener('click',event=>{const action=event.target.dataset.excelAction;if(!action)return;this[action]?.();}); }
  addCompany() { const name=prompt('Company name:','New company');if(!name?.trim())return;this.mutate(excel=>{const company=createCompany(name.trim());excel.companies.push(company);excel.selectedCompanyId=company.id;}); }
  deleteCompany() { const company=this.company;if(!company)return;const typed=prompt(`Type “${company.name}” to permanently delete this company. This can be undone.`);if(typed!==company.name){if(typed!==null)this.report('Company name did not match; nothing was deleted.');return;}this.mutate(excel=>{excel.companies=excel.companies.filter(item=>item.id!==company.id);excel.selectedCompanyId=excel.companies[0]?.id||null;}); }
  addShareholder() { if(!this.company||this.company.shareholders.length>=100)return this.report('The 100-shareholder limit has been reached.');this.mutate(excel=>{const company=excel.companies.find(item=>item.id===excel.selectedCompanyId),at=this.focus.holderId?company.shareholders.findIndex(item=>item.id===this.focus.holderId)+1:company.shareholders.length;const holder={id:`holder-${crypto.randomUUID()}`,name:'',type:'Individual'};company.shareholders.splice(at,0,holder);this.focus={holderId:holder.id};}); }
  removeShareholder() { const company=this.company,holder=company?.shareholders.find(item=>item.id===this.focus.holderId);if(!holder)return this.report('Focus a shareholder row first.');const blocking=findBlocking(company,null,holder.id,this.getDocument().steps);if(blocking)return this.blocked(blocking);this.mutate(excel=>{const current=excel.companies.find(item=>item.id===company.id);current.shareholders=current.shareholders.filter(item=>item.id!==holder.id);}); }
  addGroup() { if(!this.company)return; if(classesOf(this.company).length>=100)return this.report('The 100-share-class limit has been reached.');this.mutate(excel=>{const company=excel.companies.find(item=>item.id===excel.selectedCompanyId);company.groups.push({id:`group-${crypto.randomUUID()}`,name:'New group',classes:[{id:`class-${crypto.randomUUID()}`,label:''}]});}); }
  removeGroup() { const company=this.company,group=company?.groups.find(item=>item.id===this.focus.groupId);if(!group)return this.report('Focus a share-group header first.');const blocking=findBlocking(company,group.classes.map(item=>item.id),null,this.getDocument().steps);if(blocking)return this.blocked(blocking);this.mutate(excel=>excel.companies.find(item=>item.id===company.id).groups=company.groups.filter(item=>item.id!==group.id)); }
  addClass() { if(!this.company)return;if(classesOf(this.company).length>=100)return this.report('The 100-share-class limit has been reached.');this.mutate(excel=>{const company=excel.companies.find(item=>item.id===excel.selectedCompanyId),group=company.groups.find(item=>item.id===this.focus.groupId)||company.groups.at(-1);if(!group)return this.report('Add a share group first.');const at=this.focus.classId?group.classes.findIndex(item=>item.id===this.focus.classId)+1:group.classes.length;group.classes.splice(at,0,{id:`class-${crypto.randomUUID()}`,label:''});}); }
  removeClass() { const company=this.company,shareClass=classesOf(company||{groups:[]}).find(item=>item.id===this.focus.classId);if(!shareClass)return this.report('Focus a share-class header first.');const blocking=findBlocking(company,[shareClass.id],null,this.getDocument().steps);if(blocking)return this.blocked(blocking);this.mutate(excel=>{for(const group of excel.companies.find(item=>item.id===company.id).groups)group.classes=group.classes.filter(item=>item.id!==shareClass.id);}); }
  blocked(item) { this.report(`${this.company.name} — ${item.location}: ${item.holder.name}, ${item.shareClass.label||'unnamed share class'} contains data and blocks deletion.`); }
  table(title, values, editable, stepId='') { const company=this.company,classes=classesOf(company),summary=totals(company,values);let groupHeaders='',classHeaders='';for(const group of company.groups){groupHeaders+=`<th class="group-head" data-group-id="${escapeHtml(group.id)}" colspan="${Math.max(1,group.classes.length)}"><input value="${escapeHtml(group.name)}" aria-label="Share group"></th>`;for(const item of group.classes)classHeaders+=`<th data-group-id="${escapeHtml(group.id)}" data-class-id="${escapeHtml(item.id)}"><input value="${escapeHtml(item.label)}" aria-label="Share class"></th>`;}const rows=company.shareholders.map((holder,row)=>`<tr><th><input data-holder-name value="${escapeHtml(holder.name)}"></th><td><select data-holder-type>${TYPES.map(type=>`<option${type===holder.type?' selected':''}>${type}</option>`).join('')}</select></td>${classes.map((item,column)=>{const value=valueAt(values,holder.id,item.id),negative=value<0&&(editable==='opening'||!editable);return `<td class="number ${negative?'negative':''}" tabindex="0" data-row="${row}" data-column="${column}" data-holder-id="${escapeHtml(holder.id)}" data-class-id="${escapeHtml(item.id)}" data-step-id="${escapeHtml(stepId)}" data-editable="${editable?'true':'false'}">${formatShares(value)}</td>`;}).join('')}<td class="number total" tabindex="0">${formatShares(summary.rows[holder.id])}</td></tr>`).join('');return `<section class="share-table"><h3>${escapeHtml(title)}</h3><div class="table-scroll"><table><thead><tr><th rowspan="2">Shareholder</th><th rowspan="2">Type</th>${groupHeaders}<th rowspan="2">Total</th></tr><tr>${classHeaders}</tr></thead><tbody>${rows}<tr class="total-row"><th colspan="2">Total</th>${classes.map(item=>`<td class="number">${formatShares(summary.columns[item.id])}</td>`).join('')}<td class="number">${formatShares(summary.grand)}</td></tr></tbody></table></div></section>`; }
  render() { const excel=this.excel,company=this.company;this.root.innerHTML=`<div class="company-tabs" role="tablist">${excel.companies.map(item=>`<button role="tab" aria-selected="${item.id===excel.selectedCompanyId}" data-company-id="${escapeHtml(item.id)}">${escapeHtml(item.name)}</button>`).join('')}</div>${company?this.table('Opening Position',company.opening,'opening')+this.getDocument().steps.map((step,index)=>`<section class="step-share-section"><button class="collapse-step" data-collapse="${escapeHtml(step.id)}" aria-expanded="${!company.collapsed[step.id]}">${company.collapsed[step.id]?'▸':'▾'} Step ${index+1}: ${escapeHtml(step.title)}</button><div ${company.collapsed[step.id]?'hidden':''}>${this.table(`Step ${index+1} Movement`,company.movements[step.id],true,step.id)}${this.table(`Step ${index+1} Resulting Position`,resultingValues(company,this.getDocument().steps,index),false,step.id)}</div></section>`).join(''):'<p>Add a company to begin.</p>'}`;this.bindGrid(); }
  bindGrid() { this.root.querySelectorAll('[data-company-id]').forEach(button=>button.onclick=()=>this.mutate(excel=>excel.selectedCompanyId=button.dataset.companyId));this.root.querySelectorAll('[data-collapse]').forEach(button=>button.onclick=()=>this.mutate(excel=>{const company=excel.companies.find(item=>item.id===excel.selectedCompanyId);company.collapsed[button.dataset.collapse]=!company.collapsed[button.dataset.collapse];}));this.root.querySelectorAll('[data-holder-id],[data-holder-name]').forEach(element=>element.onfocus=()=>{const row=element.closest('tr');this.focus.holderId=row.querySelector('[data-holder-id]')?.dataset.holderId;});this.root.querySelectorAll('[data-group-id]').forEach(element=>element.onfocus=()=>{this.focus.groupId=element.dataset.groupId;this.focus.classId=element.dataset.classId;});this.root.querySelectorAll('td[data-editable=true]').forEach(cell=>{cell.ondblclick=()=>{cell.contentEditable='true';cell.focus();};cell.onfocus=()=>{this.focus={holderId:cell.dataset.holderId,classId:cell.dataset.classId,groupId:cell.closest('table').querySelector(`[data-class-id="${CSS.escape(cell.dataset.classId)}"]`)?.dataset.groupId};};cell.onblur=()=>this.commitCell(cell);cell.onkeydown=event=>this.keydown(event,cell);});this.root.querySelectorAll('[data-holder-name]').forEach(input=>input.onchange=()=>this.mutate(excel=>excel.companies.find(item=>item.id===excel.selectedCompanyId).shareholders.find(item=>item.id===this.focus.holderId).name=input.value));this.root.querySelectorAll('[data-holder-type]').forEach(select=>select.onchange=()=>this.mutate(excel=>excel.companies.find(item=>item.id===excel.selectedCompanyId).shareholders.find(item=>item.id===this.focus.holderId).type=select.value)); }
  commitCell(cell) { if(cell.contentEditable!=='true')return;const value=parseShares(cell.textContent);if(value===null){this.report('Only whole integers are permitted.');this.render();return;}this.mutate(excel=>{const company=excel.companies.find(item=>item.id===excel.selectedCompanyId),values=cell.dataset.stepId?company.movements[cell.dataset.stepId]:company.opening;values[cellKey(cell.dataset.holderId,cell.dataset.classId)]=value;}); }
  keydown(event,cell) { if(event.key==='Escape'){event.preventDefault();this.render();return;}if(['Delete','Backspace'].includes(event.key)&&cell.contentEditable!=='true')event.preventDefault();if(!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Enter','Tab'].includes(event.key))return;event.preventDefault();this.commitCell(cell);const cells=[...this.root.querySelectorAll('td[data-editable=true]')],index=cells.findIndex(item=>item.dataset.holderId===cell.dataset.holderId&&item.dataset.classId===cell.dataset.classId&&item.dataset.stepId===cell.dataset.stepId),delta=(event.key==='ArrowUp'||(event.key==='Enter'&&event.shiftKey))?-classesOf(this.company).length:(event.key==='ArrowDown'||event.key==='Enter')?classesOf(this.company).length:(event.key==='ArrowLeft'||(event.key==='Tab'&&event.shiftKey))?-1:1;cells[(index+delta+cells.length)%cells.length]?.focus(); }
}
