export const SCHEMA_VERSION=1;
export const safeHref=h=>{if(typeof h!=='string')return null;return /^(https?:\/\/|mailto:|#[A-Za-z][\w:.-]*)/i.test(h)?h:null};
const id=(v,p='id')=>/^[A-Za-z][\w-]*$/.test(v||'')?v:`${p}-${crypto.randomUUID?.()||Math.random().toString(36).slice(2)}`;
export function normaliseRuns(runs){return (Array.isArray(runs)?runs:[]).map(r=>({text:String(r?.text??''),highlight:r?.highlight===true,link:safeHref(r?.link?.href)?{href:safeHref(r.link.href)}:null})).filter(r=>r.text).reduce((a,r)=>{const x=a.at(-1);if(x&&x.highlight===r.highlight&&x.link?.href===r.link?.href)x.text+=r.text;else a.push(r);return a},[])}
export function normaliseBlock(b){
 const type=['heading','paragraph','bulletList','numberList','table'].includes(b?.type)?b.type:'paragraph',out={id:id(b?.id,'block'),type};
 if(type==='heading'){out.level=Math.min(4,Math.max(1,Number(b.level)||1));out.runs=normaliseRuns(b.runs)}
 else if(type==='paragraph')out.runs=normaliseRuns(b.runs);
 else if(type==='table'){
  const sourceColumns=Array.isArray(b.columns)?b.columns:[],count=Math.max(1,sourceColumns.length,...(Array.isArray(b.rows)?b.rows:[]).map(r=>Array.isArray(r.cells)?r.cells.length:0));
  out.columns=Array.from({length:count},(_,i)=>({id:id(sourceColumns[i]?.id,`column-${i+1}`),width:Math.max(8,Number(sourceColumns[i]?.width)||100/count)}));
  const total=out.columns.reduce((n,c)=>n+c.width,0);out.columns.forEach(c=>c.width=c.width/total*100);
  out.rows=(Array.isArray(b.rows)?b.rows:[]).map((r,ri)=>({id:id(r?.id,`row-${ri+1}`),cells:out.columns.map((_,ci)=>({id:id(r?.cells?.[ci]?.id,`cell-${ri+1}-${ci+1}`),runs:normaliseRuns(r?.cells?.[ci]?.runs)}))}));
  out.headerRow=b.headerRow===true;
  const totalColumnId=typeof b.totalColumn==='string'?b.totalColumn:b.totalColumn?.columnId;
  out.totalColumn=out.columns.some(c=>c.id===totalColumnId)?{columnId:totalColumnId,precision:Math.min(12,Math.max(0,Number.isInteger(+b.totalColumn?.precision)?+b.totalColumn.precision:2)),label:String(b.totalColumn?.label??'Total')}:null;
 }else out.items=(Array.isArray(b.items)?b.items:[]).map(i=>({id:id(i?.id,'item'),level:Math.min(3,Math.max(1,Number(i?.level)||1)),runs:normaliseRuns(i?.runs)}));return out}
export function normaliseDocument(d){const meta={};for(const k of ['clientName','projectTitle','documentType','date','version','subtitle','adviser','status'])meta[k]=String(d?.meta?.[k]??'');const groups=k=>(Array.isArray(d?.[k])?d[k]:[]).map(x=>({id:id(x?.id,k.slice(0,-1)),title:String(x?.title??''),blocks:(Array.isArray(x?.blocks)?x.blocks:[]).map(normaliseBlock)}));return{schemaVersion:SCHEMA_VERSION,meta,sections:groups('sections'),steps:groups('steps')}}
export function validateDocument(d){const n=normaliseDocument(d);if(d?.schemaVersion!==SCHEMA_VERSION)throw Error('Unsupported schema version');return n}
export const seedDocument=normaliseDocument({schemaVersion:1,meta:{clientName:'Example Client Ltd',projectTitle:'Corporate Restructure',documentType:'Steps Plan',subtitle:'Detailed Steps Plan',date:'25 July 2026',version:'v1',adviser:'UBTA Accountants Ltd',status:'Draft'},sections:[{id:'scope',title:'Scope of works',blocks:[{id:'scope-h',type:'heading',level:2,runs:[{text:'Purpose and scope'}]},{id:'scope-p1',type:'paragraph',runs:[{text:'This plan outlines the principal implementation steps for a proposed corporate restructure.'}]},{id:'scope-p2',type:'paragraph',runs:[{text:'Figures and legal mechanics marked for review require completion before finalisation.',highlight:true}]},{id:'scope-list',type:'bulletList',items:[{id:'si1',level:1,runs:[{text:'Confirm commercial objectives'}]},{id:'si2',level:2,runs:[{text:'Review supporting records'}]},{id:'si3',level:1,runs:[{text:'Consult the ',link:null},{text:'HMRC guidance',link:{href:'https://www.gov.uk/government/organisations/hm-revenue-customs'}}]}]}]}],steps:[{id:'share-restructure',title:'Implement the corporate share restructure',blocks:[{id:'step-h',type:'heading',level:2,runs:[{text:'Implementation'}]},{id:'step-p1',type:'paragraph',runs:[{text:'The directors will approve the proposed corporate restructure and authorise the required documentation.'}]},{id:'step-p2',type:'paragraph',runs:[{text:'Professional advisers should confirm the sequence immediately before implementation.'}]},{id:'step-list',type:'numberList',items:[{id:'st1',level:1,runs:[{text:'Prepare board minutes and resolutions.'}]},{id:'st2',level:2,runs:[{text:'Check company records and statutory filings.'}]},{id:'st3',level:1,runs:[{text:'Complete and retain the signed documents.'}]}]}]}]});
