import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
const modules=['state/schema.js','state/history.js','state/derived.js','state/steps.js','dom-runs.js','render.js','main.js'];
const javascript=modules.map(file=>fs.readFileSync(path.join(root,'src',file),'utf8').replace(/^import .*;\n/gm,'').replace(/export /g,'')).join('\n');
const css=['app.css','document.css'].map(file=>fs.readFileSync(path.join(root,'src/styles',file),'utf8')).join('\n');
const vendor=fs.readFileSync(path.join(root,'src/vendor/paged.js'),'utf8');
const body=fs.readFileSync(path.join(root,'src/index.html'),'utf8').match(/<body>([\s\S]*)<\/body>/)[1].replace(/<script[\s\S]*?<\/script>/g,'');
const html=`<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>UBTA Steps Plan Editor</title><style>${css}</style></head><body>${body}<script>${vendor}\n${javascript}<\/script></body></html>`;
fs.mkdirSync(path.join(root,'dist'),{recursive:true});fs.writeFileSync(path.join(root,'dist/index.html'),html);console.log(`Built dist/index.html (${html.length} bytes)`);
