import assert from 'node:assert/strict';import test from 'node:test';import {webcrypto} from 'node:crypto';
import {decryptEnvelope,validateEnvelope,DAMAGED_FILE_MESSAGE} from '../src/editor/crypto.js';import {EncryptedTemplateLoader,templateBlocks,validateTemplatePayload} from '../src/editor/default-templates.js';import {insertionIndex} from '../src/editor/insertion-context.js';import {History} from '../src/state/history.js';
const valid={type:'editor-defaults',templates:[{id:'stamp',header:'Stamp duty',body:'Body'}]};
test('validates records and preserves header labels',()=>assert.deepEqual(validateTemplatePayload(valid).map(x=>x.header),['Stamp duty']));
test('rejects malformed decrypted payloads and duplicate ids',()=>{for(const payload of [null,{type:'wrong',templates:[]},{type:'editor-defaults',templates:[{id:'x',header:'',body:'b'}]},{type:'editor-defaults',templates:[{id:'x',header:'a',body:'b'},{id:'x',header:'c',body:'d'}]}])assert.throws(()=>validateTemplatePayload(payload),/malformed/)});
test('password retry caches only a successful in-memory result',async()=>{let calls=0;const loader=new EncryptedTemplateLoader({decrypt:async(_envelope,password)=>{calls++;if(password!=='right')throw Error(DAMAGED_FILE_MESSAGE);return valid}});await assert.rejects(loader.unlock({},'wrong'),/Incorrect password/);assert.equal(loader.cached,false);assert.equal((await loader.unlock({},'right'))[0].header,'Stamp duty');await loader.unlock({},'ignored');assert.equal(calls,2)});
test('template pair inserts at beginning, middle and end and is atomic in history',()=>{for(const context of [{groupId:'g',referenceBlockId:'a',position:'before'},{groupId:'g',referenceBlockId:'a',position:'after'},{groupId:'g',referenceBlockId:null,position:'after'}]){const group={id:'g',blocks:[{id:'a'}]},history=new History(group),pair=templateBlocks(valid.templates[0],p=>`${p}-${Math.random()}`),at=insertionIndex(group,context);group.blocks.splice(at,0,...pair);history.commit(group);assert.equal(history.checkout().blocks.length,3);assert.equal(history.undo().blocks.length,1)}});
test('changed targets preserve the captured group and safely use its end',()=>{const group={id:'g',blocks:[{id:'changed'}]};assert.equal(insertionIndex(group,{groupId:'g',referenceBlockId:'deleted',position:'before'}),1);assert.equal(insertionIndex(group,{groupId:'other'}),-1)});
test('envelope failures have a generic error',async()=>{const b=n=>Buffer.alloc(n).toString('base64'),bad={version:1,algorithm:'AES-GCM',kdf:'PBKDF2-SHA-256',iterations:310000,salt:b(16),iv:b(12),ciphertext:b(17)};assert.doesNotThrow(()=>validateEnvelope(bad));await assert.rejects(decryptEnvelope(bad,'wrong',webcrypto.subtle),/Incorrect password or damaged file/);assert.throws(()=>validateEnvelope({...bad,iv:'no'}),/Incorrect password or damaged file/)});
