import test from 'node:test';import assert from 'node:assert/strict';
import fs from 'node:fs';
import { transformRuns, runsFromElement, insertPlainText } from '../src/editor/dom-runs.js';
import { validatedLink, confirmStepDeletion, splitListRuns, insertTableRowBeforeTotals, GenerationGate, restoreTextSelection } from '../src/editor/interactions.js';
const fixture=JSON.parse(fs.readFileSync(new URL('./fixtures/rich-runs.json',import.meta.url)));const runs=[fixture.runs[0],{...fixture.runs[2],text:'linked',link:{href:'#anchor-a'}},{...fixture.runs[3],text:'web'}];
test('highlighting mixed runs preserves links',()=>{const out=transformRuns(runs,[2,12],'highlight');assert.equal(out.map(x=>x.text).join(''),'plainlinkedweb');assert.ok(out.filter(x=>x.text.includes('linked')).every(x=>x.link?.href==='#anchor-a'))});
test('link and unlink are selection-only and preserve highlight',()=>{let out=transformRuns(runs,[5,11],'link','mailto:a@b.test');assert.equal(out.find(x=>x.text==='linked').highlight,true);out=transformRuns(out,[6,9],'unlink');assert.equal(out.map(x=>x.text).join(''),'plainlinkedweb');assert.ok(out.some(x=>x.text==='ink'&&!x.link))});
test('nested markup retains combined link and highlight',()=>{const text={nodeType:3,nodeValue:'nested'},span={nodeType:1,tagName:'SPAN',childNodes:[text],nextSibling:null},anchor={nodeType:1,tagName:'A',childNodes:[span],nextSibling:null,getAttribute:()=> '#anchor-a'},mark={nodeType:1,tagName:'MARK',childNodes:[anchor],nextSibling:null,getAttribute:()=>null};assert.deepEqual(runsFromElement({childNodes:[mark]}),[{text:'nested',highlight:true,link:{href:'#anchor-a'}}])});
test('paste inserts only plain text',()=>{let prevented=false,args;insertPlainText({preventDefault:()=>prevented=true,clipboardData:{getData:type=>type==='text/plain'?'safe':'<b>unsafe</b>'}},{execCommand:(...x)=>args=x});assert.equal(prevented,true);assert.deepEqual(args,['insertText',false,'safe'])});
test('list splitting preserves rich formatting',()=>{const [a,b]=splitListRuns(runs,7);assert.equal(a.map(x=>x.text).join(''),'plainli');assert.equal(b[0].highlight,true);assert.equal(b[0].link.href,'#anchor-a')});
test('table insertion precedes totals',()=>{let id=0;const block={columns:[{},{}],rows:[{isTotal:false},{isTotal:true}]};assert.equal(insertTableRowBeforeTotals(block,p=>`${p}-${++id}`),1);assert.equal(block.rows[2].isTotal,true);assert.equal(block.rows[1].cells.length,2)});
test('step deletion protects final step and confirms visible title',()=>{assert.equal(confirmStepDeletion([{title:'Only'}],0,()=>true),false);let message;assert.equal(confirmStepDeletion([{title:'One'},{title:'Two'}],1,x=>(message=x,true)),true);assert.match(message,/Step 2: Two/)});
test('validated links prefer external and reject unsafe input',()=>{assert.equal(validatedLink('', '#anchor-a'),'#anchor-a');assert.equal(validatedLink(' https://example.test ','#anchor-a'),'https://example.test');assert.equal(validatedLink('javascript:x','#anchor-a'),null)});
test('generation gate rejects stale pagination',()=>{const gate=new GenerationGate,a=gate.next(),b=gate.next();assert.equal(gate.isCurrent(a),false);assert.equal(gate.isCurrent(b),true)});
test('selection restoration focuses without scrolling and publishes range',()=>{const node={length:5},calls=[];const range={setStart:(...x)=>calls.push(['start',...x]),setEnd:(...x)=>calls.push(['end',...x])};const environment={NodeFilter:{SHOW_TEXT:4},document:{createTreeWalker:()=>({nextNode:(()=>{let once=false;return()=>once?null:(once=true,node)})()}),createRange:()=>range},getSelection:()=>({removeAllRanges(){},addRange:r=>calls.push(['range',r])})};let option;assert.equal(restoreTextSelection({focus:x=>option=x},[1,4],environment),true);assert.deepEqual(option,{preventScroll:true});assert.equal(calls.at(-1)[0],'range')});

test('debounced input produces one history operation',async()=>{const { History }=await import('../src/state/history.js');let text='';const history=new History({text});const scheduler=new (await import('../src/editor/repagination.js')).RepaginationScheduler(async()=>{history.commit({text});return true},{delay:5});text='a';scheduler.request();text='ab';scheduler.request();text='abc';await scheduler.request();assert.equal(history.past.length,1);assert.deepEqual(history.undo(),{text:''});assert.deepEqual(history.redo(),{text:'abc'})});
