import test from 'node:test';
import assert from 'node:assert/strict';
import { createCompany, createExcel, parseShares, formatShares, syncSteps, resultingValues, totals, cellKey, findBlocking, applyPaste, stepHasMovements, normaliseExcel } from '../src/state/excel-model.js';

test('default company contains the required zero-valued structure', () => { const company=createCompany();assert.deepEqual(company.shareholders.map(item=>item.type),['Individual','Trust','Company']);assert.deepEqual(company.groups.map(item=>item.name),['Ordinary Shares','Preference Shares','Deferred Shares']);assert.ok(company.groups.every(group=>group.classes.length===1));assert.deepEqual(company.opening,{}); });
test('whole shares parse and format negatives while rejecting decimals', () => { assert.equal(parseShares('(1,200)'),-1200);assert.equal(parseShares('-100'),-100);assert.equal(parseShares(''),0);assert.equal(parseShares('1.5'),null);assert.equal(formatShares(-1234),'(1,234)'); });
test('step synchronization uses stable identity through reorder, rename and deletion', () => { const excel=createExcel(),company=excel.companies[0],key=cellKey(company.shareholders[0].id,company.groups[0].classes[0].id);company.movements={a:{[key]:5}};let synced=syncSteps(excel,[{id:'a',title:'Old'},{id:'b',title:'New'}]);synced=syncSteps(synced,[{id:'b',title:'First'},{id:'a',title:'Renamed'}]);assert.equal(synced.companies[0].movements.a[key],5);assert.deepEqual(synced.syncedSteps.map(item=>item.id),['b','a']);synced=syncSteps(synced,[{id:'b',title:'First'}]);assert.equal(synced.companies[0].movements.a,undefined); });
test('positions chain and row, column and grand totals are derived', () => { const company=createCompany(),shareClass=company.groups[0].classes[0],holder=company.shareholders[0],key=cellKey(holder.id,shareClass.id),steps=[{id:'a'},{id:'b'}];company.opening[key]=10;company.movements={a:{[key]:-3},b:{[key]:8}};const result=resultingValues(company,steps,1),summary=totals(company,result);assert.equal(result[key],15);assert.equal(summary.rows[holder.id],15);assert.equal(summary.columns[shareClass.id],15);assert.equal(summary.grand,15); });
test('deletion finds editable blocking data by step and movements are detectable', () => { const company=createCompany(),shareClass=company.groups[0].classes[0],holder=company.shareholders[0],key=cellKey(holder.id,shareClass.id);company.movements={a:{[key]:2}};assert.equal(findBlocking(company,[shareClass.id],null,[{id:'a',title:'Issue shares'}]).location,'Issue shares');assert.equal(stepHasMovements({companies:[company]},'a'),true); });
test('paste modes are atomic and reject ranges that do not fit', () => { const company=createCompany(),key=cellKey(company.shareholders[0].id,company.groups[0].classes[0].id);let values=applyPaste(company,{[key]:10},0,0,[[2]],'add');assert.equal(values[key],12);assert.equal(applyPaste(company,values,0,0,[[2]],'subtract')[key],10);assert.equal(applyPaste(company,values,0,0,[[2]],'negative')[key],-2);assert.throws(()=>applyPaste(company,values,2,2,[[1,2]]),/does not fit/);assert.equal(values[key],12); });
test('normalization enforces 100 row and class safety limits', () => { const company=createCompany();company.shareholders=Array.from({length:101},(_,index)=>({id:`h${index}`,name:'H',type:'Trust'}));company.groups=[{id:'g',name:'G',classes:Array.from({length:101},(_,index)=>({id:`c${index}`,label:''}))}];const clean=normaliseExcel({companies:[company]},[]).companies[0];assert.equal(clean.shareholders.length,100);assert.equal(clean.groups[0].classes.length,100); });
