import test from 'node:test';
import assert from 'node:assert/strict';
import { createRepaginationScheduler } from '../src/state/repagination.js';
function timers(){const jobs=new Map();let id=0;return{setTimer(fn){jobs.set(++id,fn);return id},clearTimer(key){jobs.delete(key)},async flush(){const queued=[...jobs.values()];jobs.clear();for(const fn of queued)await fn()},get size(){return jobs.size}}}
test('rapid layout edits coalesce into one pagination',async()=>{const clock=timers();let renders=0;const scheduler=createRepaginationScheduler({render:async()=>{renders++},setTimer:clock.setTimer,clearTimer:clock.clearTimer});scheduler.request();scheduler.request();scheduler.request();assert.equal(clock.size,1);await clock.flush();assert.equal(renders,1)});
test('new input can cancel a queued pagination until its state is synchronized',async()=>{const clock=timers();let renders=0;const scheduler=createRepaginationScheduler({render:async()=>{renders++},setTimer:clock.setTimer,clearTimer:clock.clearTimer});scheduler.request();scheduler.cancel();assert.equal(clock.size,0);await clock.flush();assert.equal(renders,0);scheduler.request();await clock.flush();assert.equal(renders,1)});
test('a newer request cancels completion of a stale render',async()=>{const resolvers=[],restored=[];const scheduler=createRepaginationScheduler({render:()=>new Promise(resolve=>resolvers.push(resolve)),capture:()=>scheduler.generation,restore:view=>restored.push(view)});const first=scheduler.request({immediate:true}),second=scheduler.request({immediate:true});resolvers[0]();assert.equal(await first,false);assert.deepEqual(restored,[]);resolvers[1]();assert.equal(await second,true);assert.deepEqual(restored,[2])});
test('structural changes bypass the debounce',async()=>{const clock=timers();let renders=0;const scheduler=createRepaginationScheduler({render:async()=>{renders++},setTimer:clock.setTimer,clearTimer:clock.clearTimer});scheduler.request();await scheduler.request({immediate:true});assert.equal(clock.size,0);assert.equal(renders,1)});
test('page, scroll, active block and selection are restored after replacement',async()=>{const view={page:3,scrollY:420,activeBlockId:'block-7',offsets:[2,5]};let restored;const scheduler=createRepaginationScheduler({capture:()=>structuredClone(view),render:async()=>{},restore:snapshot=>{restored=snapshot}});await scheduler.request({immediate:true});assert.deepEqual(restored,view)});
