import test from 'node:test';
import assert from 'node:assert/strict';
import { SCHEMA_VERSION, normaliseDocument, normaliseBlock, normaliseRuns, normaliseTableWidths, safeHref, safeImageSrc, seedDocument, transactionProposals, validateDocument, hasReview, stableAnchor } from '../src/state/schema.js';
import { History } from '../src/state/history.js';

test('seed satisfies current closed schema',()=>assert.equal(validateDocument(seedDocument).schemaVersion,SCHEMA_VERSION));
test('unknown formatting is reduced and newlines survive',()=>assert.deepEqual(normaliseRuns([{text:'a\r\nb',highlight:true,unknown:1}]),[{text:'a\nb',highlight:true,link:null}]));
test('links permit approved protocols only',()=>{assert.equal(safeHref('javascript:alert(1)'),null);assert.equal(safeHref('#anchor-ok'),'#anchor-ok');assert.equal(safeHref('https://example.test'),'https://example.test')});
test('images allow empty alt but require a safe supported source',()=>{assert.equal(safeImageSrc('data:image/png;base64,YQ=='),'data:image/png;base64,YQ==');assert.equal(safeImageSrc('https://example.test/a.png'),'https://example.test/a.png');assert.equal(safeImageSrc('https://example.test/a.svg'),null);const d=validateDocument({schemaVersion:SCHEMA_VERSION,steps:[{blocks:[{type:'image',src:'https://example.test/a.png',alt:''}]}]});assert.equal(d.steps[0].blocks[0].alt,'');assert.throws(()=>validateDocument({schemaVersion:SCHEMA_VERSION,steps:[{blocks:[{type:'image',src:'javascript:x'}]}]}),/safe source/)});
test('bounded width redistribution handles pathological and malformed widths',()=>{for(const input of [[96.678,87.036,8.385],[1000,1,1],[8,8,84],[92,4,4],[33.333,33.333,33.333],[NaN,-2,Infinity,10]]){const widths=normaliseTableWidths(input,input.length);assert.ok(widths.every(x=>x>=8&&x<=92),String(widths));assert.ok(Math.abs(widths.reduce((a,b)=>a+b,0)-100)<.002,String(widths))}});
test('tables provide stable matching cells and rich headings/caption',()=>{const b=normaliseBlock({type:'table',caption:'Caption',columns:[{heading:'A'},{heading:'B'}],rows:[{cells:[{runs:[{text:'x'}]}]}]});assert.equal(b.rows[0].cells.length,2);assert.equal(b.captionRuns[0].text,'Caption');assert.equal(b.columns[0].headingRuns[0].text,'A')});
test('appendices migrate with stable anchors',()=>{const d=normaliseDocument({schemaVersion:2,appendices:[{id:'rates',title:'Rates',blocks:[]}]});assert.equal(d.appendices[0].id,'rates');assert.equal(stableAnchor(d.appendices[0]),'anchor-rates')});
test('proposal summaries use a trimmed override or first eligible body content',()=>{for(const summary of [undefined,'','   ']){const p=transactionProposals({steps:[{id:'s',summary,blocks:[{type:'heading',runs:[{text:'Heading'}]},{type:'paragraph',runs:[]},{type:'paragraph',runs:[{text:'Fallback'}]}]}]})[0];assert.equal(p.summary,'Fallback')}assert.equal(transactionProposals({steps:[{id:'s',summary:' Deliberate ',blocks:[{type:'paragraph',runs:[{text:'Fallback'}]}]}]})[0].summary,'Deliberate')});
test('review traversal covers headings, paragraphs, lists, captions, cells, and image captions',()=>{for(const block of [{type:'heading',runs:[{text:'x',highlight:true}]},{type:'paragraph',runs:[{text:'x',highlight:true}]},{type:'bulletList',items:[{runs:[{text:'x',highlight:true}]}]},{type:'table',captionRuns:[{text:'x',highlight:true}],columns:[{heading:'A'}],rows:[]},{type:'table',columns:[{heading:'A'}],rows:[{cells:[{runs:[{text:'x',highlight:true}]}]}]},{type:'image',src:'https://x.test/x.png',captionRuns:[{text:'x',highlight:true}]}])assert.equal(hasReview({blocks:[normaliseBlock(block)]}),true)});
test('normalisation retains highlight and links together',()=>assert.deepEqual(normaliseRuns([{text:'x',highlight:true,link:{href:'#anchor-a'}}]),[{text:'x',highlight:true,link:{href:'#anchor-a'}}]));
test('history rejects no-op entries and undo reverses one operation',()=>{const h=new History({x:1});assert.equal(h.commit({x:1}),false);h.commit({x:2});assert.equal(h.past.length,1);assert.deepEqual(h.undo(),{x:1})});
test('history checkout detaches mutable editor state from its snapshot',()=>{const h=new History({text:'before'}),draft=h.checkout();draft.text='after';assert.deepEqual(h.value,{text:'before'});assert.equal(h.commit(draft),true);assert.deepEqual(h.undo(),{text:'before'})});
