import test from 'node:test';
import assert from 'node:assert/strict';
import { SCHEMA_VERSION, normaliseDocument, normaliseBlock, normaliseRuns, normaliseTableWidths, safeHref, safeImageSrc, seedDocument, transactionProposals, validateDocument, hasReview, stableAnchor } from '../src/state/schema.js';
import { History } from '../src/state/history.js';

test('seed satisfies current closed schema',()=>assert.equal(validateDocument(seedDocument).schemaVersion,SCHEMA_VERSION));
test('unknown formatting is reduced and newlines survive',()=>assert.deepEqual(normaliseRuns([{text:'a\r\nb',highlight:true,unknown:1}]),[{text:'a\nb',highlight:true,link:null}]));
test('links permit approved protocols only',()=>{assert.equal(safeHref('javascript:alert(1)'),null);assert.equal(safeHref('#anchor-ok'),'#anchor-ok');assert.equal(safeHref('https://example.test'),'https://example.test')});
test('images require published HTTPS sources with supported path extensions',()=>{assert.equal(safeImageSrc('data:image/png;base64,YQ=='),null);assert.equal(safeImageSrc('http://example.test/a.png'),null);assert.equal(safeImageSrc('https://example.test/a.png?version=2'),'https://example.test/a.png?version=2');assert.equal(safeImageSrc('https://example.test/a.svg'),null);assert.equal(safeImageSrc('https://example.test/image?file=a.png'),null);assert.equal(safeImageSrc('not a URL'),null);const d=validateDocument({schemaVersion:SCHEMA_VERSION,steps:[{blocks:[{type:'image',src:'https://example.test/a.jpeg',alt:'Example'}]}]});assert.equal(d.steps[0].blocks[0].src,'https://example.test/a.jpeg');assert.throws(()=>validateDocument({schemaVersion:SCHEMA_VERSION,steps:[{blocks:[{type:'image',src:'javascript:x'}]}]}),/supported .* HTTPS source/)});
test('legacy embedded images are rejected with migration guidance',()=>assert.throws(()=>validateDocument({schemaVersion:3,steps:[{blocks:[{type:'image',src:'data:image/png;base64,YQ==',alt:'Legacy'}]}]}),/Legacy embedded data-URL images.*publish the image over HTTPS/));
test('bounded width redistribution handles pathological and malformed widths',()=>{for(const input of [[96.678,87.036,8.385],[1000,1,1],[8,8,84],[92,4,4],[33.333,33.333,33.333],[NaN,-2,Infinity,10]]){const widths=normaliseTableWidths(input,input.length);assert.ok(widths.every(x=>x>=8&&x<=92),String(widths));assert.ok(Math.abs(widths.reduce((a,b)=>a+b,0)-100)<.002,String(widths))}});
test('tables provide stable matching cells and rich headings/caption',()=>{const b=normaliseBlock({type:'table',caption:'Caption',columns:[{heading:'A'},{heading:'B'}],rows:[{cells:[{runs:[{text:'x'}]}]}]});assert.equal(b.rows[0].cells.length,2);assert.equal(b.captionRuns[0].text,'Caption');assert.equal(b.columns[0].headingRuns[0].text,'A')});
test('appendices migrate with stable anchors',()=>{const d=normaliseDocument({schemaVersion:2,appendices:[{id:'rates',title:'Rates',blocks:[]}]});assert.equal(d.appendices[0].id,'rates');assert.equal(stableAnchor(d.appendices[0]),'anchor-rates')});
test('appendix titles and all block types survive snapshot round trips',()=>{const appendix={id:'support',title:'Supporting schedules',blocks:[{id:'p',type:'paragraph',runs:[{text:'Body'}]},{id:'h',type:'heading',level:2,runs:[{text:'Heading'}]},{id:'l',type:'bulletList',items:[{id:'i',level:1,runs:[{text:'Item'}]}]},{id:'t',type:'table',columns:[{id:'c',headingRuns:[{text:'Column'}],width:100}],rows:[]},{id:'img',type:'image',src:'https://example.test/image.png',alt:'Example',width:100}]},document=decodeSnapshot(encodeSnapshot({...seedDocument,appendices:[appendix]}));assert.equal(document.appendices[0].title,appendix.title);assert.deepEqual(document.appendices[0].blocks.map(block=>block.type),['paragraph','heading','bulletList','table','image'])});
test('appendix creation, reordering and deletion are undoable history operations',()=>{const history=new History({appendices:[]}),draft=history.checkout(),first={id:'a',title:'First',blocks:[]},second={id:'b',title:'Second',blocks:[]};draft.appendices.push(first,second);history.commit(draft);const reordered=history.checkout();reordered.appendices.reverse();history.commit(reordered);const deleted=history.checkout();deleted.appendices.splice(1,1);history.commit(deleted);assert.deepEqual(history.undo().appendices.map(x=>x.id),['b','a']);assert.deepEqual(history.undo().appendices.map(x=>x.id),['a','b']);assert.deepEqual(history.undo().appendices,[])});
test('proposal summaries use a trimmed override or first eligible body content',()=>{for(const summary of [undefined,'','   ']){const p=transactionProposals({steps:[{id:'s',summary,blocks:[{type:'heading',runs:[{text:'Heading'}]},{type:'paragraph',runs:[]},{type:'paragraph',runs:[{text:'Fallback'}]}]}]})[0];assert.equal(p.summary,'Fallback')}assert.equal(transactionProposals({steps:[{id:'s',summary:' Deliberate ',blocks:[{type:'paragraph',runs:[{text:'Fallback'}]}]}]})[0].summary,'Deliberate')});
test('review traversal covers headings, paragraphs, lists, captions, cells, and image captions',()=>{for(const block of [{type:'heading',runs:[{text:'x',highlight:true}]},{type:'paragraph',runs:[{text:'x',highlight:true}]},{type:'bulletList',items:[{runs:[{text:'x',highlight:true}]}]},{type:'table',captionRuns:[{text:'x',highlight:true}],columns:[{heading:'A'}],rows:[]},{type:'table',columns:[{heading:'A'}],rows:[{cells:[{runs:[{text:'x',highlight:true}]}]}]},{type:'image',src:'https://x.test/x.png',captionRuns:[{text:'x',highlight:true}]}])assert.equal(hasReview({blocks:[normaliseBlock(block)]}),true)});
test('normalisation retains highlight and links together',()=>assert.deepEqual(normaliseRuns([{text:'x',highlight:true,link:{href:'#anchor-a'}}]),[{text:'x',highlight:true,link:{href:'#anchor-a'}}]));
test('history rejects no-op entries and undo reverses one operation',()=>{const h=new History({x:1});assert.equal(h.commit({x:1}),false);h.commit({x:2});assert.equal(h.past.length,1);assert.deepEqual(h.undo(),{x:1})});
test('history checkout detaches mutable editor state from its snapshot',()=>{const h=new History({text:'before'}),draft=h.checkout();draft.text='after';assert.deepEqual(h.value,{text:'before'});assert.equal(h.commit(draft),true);assert.deepEqual(h.undo(),{text:'before'})});

import { STORAGE_KEYS, saveDraft, readDraft, readRecovery, saveVersion, listVersions, encodeSnapshot, decodeSnapshot } from '../src/state/persistence.js';
const memoryStorage = () => { const values=new Map(); return { getItem:key=>values.get(key)??null, setItem:(key,value)=>values.set(key,String(value)), removeItem:key=>values.delete(key) }; };
test('draft saves rotate recovery and reject stale tabs before either record changes',()=>{const storage=memoryStorage();const first=saveDraft(seedDocument,0,storage,1);assert.equal(first.ok,true);const second=saveDraft({...seedDocument,meta:{...seedDocument.meta,clientName:'Second'}},1,storage,2);assert.equal(second.ok,true);const draftBefore=storage.getItem(STORAGE_KEYS.draft),recoveryBefore=storage.getItem(STORAGE_KEYS.recovery);assert.deepEqual(readRecovery(storage).document,first.record.document);assert.deepEqual(saveDraft(seedDocument,1,storage,3),{ok:false,stale:true,revision:2});assert.equal(storage.getItem(STORAGE_KEYS.draft),draftBefore);assert.equal(storage.getItem(STORAGE_KEYS.recovery),recoveryBefore);assert.equal(readDraft(storage).revision,2)});
test('named versions are newest first and limited to twenty',()=>{const storage=memoryStorage();for(let i=0;i<25;i++)saveVersion(seedDocument,`Version ${i}`,storage,i);const versions=listVersions(storage);assert.equal(versions.length,20);assert.equal(versions[0].label,'Version 24');assert.equal(versions.at(-1).label,'Version 5')});
test('URL snapshots are versioned, unicode-safe, and validated',()=>{const document={...seedDocument,meta:{...seedDocument.meta,clientName:'Société 🧾'}};assert.equal(decodeSnapshot(encodeSnapshot(document)).meta.clientName,'Société 🧾');assert.throws(()=>decodeSnapshot('not-a-snapshot'),/Invalid UBTA snapshot/)});

test('metadata always has complete empty shape',()=>assert.deepEqual(normaliseDocument({}).meta,{clientName:'',projectTitle:'',documentType:'',date:'',version:'',subtitle:'',adviser:'',status:''}));
test('metadata rejects objects, null, invalid dates and statuses',()=>{const meta=normaliseDocument({meta:{clientName:{},projectTitle:null,date:'25 July 2026',status:'Approved'}}).meta;assert.equal(meta.clientName,'');assert.equal(meta.projectTitle,'');assert.equal(meta.date,'');assert.equal(meta.status,'')});
test('metadata trims and preserves accepted scalar values',()=>{const meta=normaliseDocument({meta:{clientName:' Client ',projectTitle:42,adviser:true,date:'2026-07-25',status:'For review'}}).meta;assert.equal(meta.clientName,'Client');assert.equal(meta.projectTitle,'42');assert.equal(meta.adviser,'true');assert.equal(meta.date,'2026-07-25');assert.equal(meta.status,'For review')});
test('metadata rejects impossible calendar dates',()=>assert.equal(normaliseDocument({meta:{date:'2026-02-30'}}).meta.date,''));
