import {createBlankCase,blankCapitalRow,blankSeller,blankShareLine} from '../data/model.js';
import {addItem,removeItem,moveItem} from '../data/operations.js';
import {validateStep,validateCase} from '../validation/validate.js';
import {installRuntimeGuards} from '../security/guards.js';
import {STEPS,renderStep} from '../ui/render.js';
import {rowAggregate,capitalTotals} from './decimal.js';
import {generateLetterPdf,letterFilename} from '../letter/index.js';
installRuntimeGuards(window);
let caseData=createBlankCase(), step=0, errors={};
const root=/** @type {HTMLElement} */(document.querySelector('#app'));
function at(path){return path.split('.').reduce((o,k)=>o[k],caseData)}
function set(path,value){const keys=path.split('.');let target=caseData;for(const key of keys.slice(0,-1))target=target[key];target[keys.at(-1)]=value;}
function render(){root.innerHTML=`<header><p class="eyebrow">UBTA · Section 77</p><h1>S77 Letter Generator</h1><p>Case information stays in this page and is discarded when it closes or reloads.</p></header><nav aria-label="Form progress"><p><strong>Step ${step+1} of ${STEPS.length}</strong> · ${STEPS[step]}</p><progress value="${step+1}" max="${STEPS.length}"></progress><ol>${STEPS.map((x,i)=>`<li class="${i===step?'current':''}">${x}</li>`).join('')}</ol></nav><main><div id="error-summary" role="alert" tabindex="-1">${Object.keys(errors).length?`<h2>There is a problem</h2><ul>${Object.entries(errors).map(([p,m])=>`<li><a href="#${p}">${m}</a></li>`).join('')}</ul>`:''}</div><h1>${STEPS[step]}</h1>${renderStep(caseData,step,errors)}<div class="navigation"><button data-action="back" ${step===0?'disabled':''}>Back</button><button class="primary" data-action="continue">${step===8?'Validate case':'Continue'}</button><button class="danger" data-action="clear">Clear case</button></div></main><footer>Offline foundation · No case information is retained</footer>`;}
root.addEventListener('input',event=>{const el=/** @type {HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement} */(event.target);if((el instanceof HTMLInputElement||el instanceof HTMLSelectElement||el instanceof HTMLTextAreaElement)&&el.dataset.path&&el.dataset.path!=='letterDate'){set(el.dataset.path,el.value.trimStart());delete errors[el.dataset.path];if(step===3){const match=el.dataset.path.match(/^form\.([^.]*)\.(\d+)\./);if(match){const [,list,index]=match;const aggregate=document.querySelector(`[data-aggregate="${list}.${index}"]`);if(aggregate)aggregate.textContent=rowAggregate(caseData.form[list][Number(index)]);const totals=capitalTotals(caseData.form[list]);const totalOutput=document.querySelector(`[data-totals="${list}"]`);if(totalOutput)totalOutput.innerHTML=`<strong>Totals:</strong> ${totals.shares} shares · ${totals.nominal}`;}}}});
root.addEventListener('change',event=>{const el=/** @type {HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement} */(event.target);if(el.dataset?.path&&el.dataset.path!=='letterDate'){set(el.dataset.path,el.value.trim());el.value=el.value.trim();}});
root.addEventListener('click',async event=>{const b=/** @type {HTMLElement} */(event.target).closest('button');if(!b||b.disabled)return;event.preventDefault();const a=b.dataset.action;
 if(a==='generate-letter'){const bytes=await generateLetterPdf(caseData,new Date());const url=URL.createObjectURL(new Blob([Uint8Array.from(bytes).buffer],{type:'application/pdf'}));const link=document.createElement('a');link.href=url;link.download=letterFilename(caseData);link.click();URL.revokeObjectURL(url);return;} if(a==='continue'){errors=step===8?validateCase(caseData):validateStep(caseData,step);if(Object.keys(errors).length){render();/** @type {HTMLElement} */(document.querySelector('#error-summary')).focus();return;}if(step<8)step++;render();return;} if(a==='back'){step--;errors={};render();return;} if(a==='clear'){if(confirm('Clear this case? All entered information and file references will be released.')){caseData=createBlankCase();step=0;errors={};render();}return;}
 if(a==='add-capital')set(`form.${b.dataset.list}`,addItem(at(`form.${b.dataset.list}`),()=>blankCapitalRow()));
 if(a==='remove-capital')set(`form.${b.dataset.list}`,removeItem(at(`form.${b.dataset.list}`),b.dataset.id));
 if(a==='add-reason')caseData.form.commercialReasons.push({id:crypto.randomUUID(),heading:'',body:''});
 if(a==='remove-reason')caseData.form.commercialReasons=removeItem(caseData.form.commercialReasons,b.dataset.id);
 if(a==='move-reason')caseData.form.commercialReasons=moveItem(caseData.form.commercialReasons,b.dataset.id,Number(b.dataset.delta));
 if(a==='add-seller')caseData.form.schedule.push(blankSeller());if(a==='remove-seller')caseData.form.schedule=removeItem(caseData.form.schedule,b.dataset.id);if(a==='move-seller')caseData.form.schedule=moveItem(caseData.form.schedule,b.dataset.id,Number(b.dataset.delta));
 const lineType=/** @type {'saleShares'|'considerationShares'} */(b.dataset.type);if(a==='add-line')caseData.form.schedule[Number(b.dataset.seller)][lineType].push(blankShareLine());if(a==='remove-line'){const s=caseData.form.schedule[Number(b.dataset.seller)];s[lineType]=removeItem(s[lineType],b.dataset.id);}render();});
render();
