import {seedDocument,normaliseDocument,normaliseRuns,safeHref,IMAGE_MIME_TYPES,MAX_IMAGE_BYTES,MAX_IMAGE_DIMENSION,MAX_IMAGE_PIXELS} from './state/schema.js';
import {History} from './state/history.js';
const history=new History(structuredClone(seedDocument));let state=history.value,currentPage=1,timer;
const $=s=>document.querySelector(s); const textRuns=r=>r.map(x=>x.text).join('');
function hasReview(group){return group.blocks.some(b=>b.type==='image'&&!b.alt||(b.runs||b.caption||b.items?.flatMap(i=>i.runs)||[]).some(r=>r.highlight))}
function header(){const x=document.createElement('header');x.className='page-header';x.setAttribute('aria-label','UBTA Accountants report header');x.innerHTML='<span class="header-brand">UBTA</span><span class="header-details">UBTA Accountants Ltd <b aria-hidden="true">·</b> Practical tax advice</span>';return x}
function sheet(kind){const x=document.createElement('section');x.className=`sheet-source ${kind}`;x.append(header());return x}
function footer(x,n,total){const f=document.createElement('footer');f.className='page-footer';f.textContent=`Page ${n} of ${total}`;x.append(f)}
function runsHTML(runs){return runs.map(r=>{let t=escapeHTML(r.text);if(r.link)t=`<a href="${escapeHTML(r.link.href)}" target="_blank" rel="noopener">${t}</a>`;return r.highlight?`<mark>${t}</mark>`:t}).join('')}
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function editable(block){const el=document.createElement('div');el.className='editable-block';el.dataset.blockId=block.id;el.dataset.type=block.type;el.dataset.level=block.level||'';el.contentEditable='true';el.lang='en-GB';el.spellcheck=true;if(block.type==='heading')el.innerHTML=runsHTML(block.runs);else if(block.type==='paragraph')el.innerHTML=runsHTML(block.runs);else{el.classList.add('list-block');el.dataset.listType=block.type;el.innerHTML=block.items.map(i=>`<div class="list-item" data-item-id="${i.id}" data-level="${i.level}" style="list-style-type:${block.type==='numberList'?'decimal':'disc'}">${runsHTML(i.runs)}</div>`).join('')}return el}
function imageBlock(block){const el=document.createElement('figure');el.className=`image-block align-${block.alignment}${block.alt?'':' needs-alt'}`;el.dataset.blockId=block.id;el.dataset.type='image';el.style.width=`${block.widthPercent}%`;el.tabIndex=0;el.setAttribute('aria-label',`Image block${block.alt?`: ${block.alt}`:'; alt text required'}`);el.innerHTML=`<div class="image-frame"><img src="${escapeHTML(block.src)}" alt="${escapeHTML(block.alt)}" width="${block.intrinsicWidth}" height="${block.intrinsicHeight}" draggable="false"><button class="resize-handle resize-left" data-resize="-1" aria-label="Resize image from left; use arrow keys for width"></button><button class="resize-handle resize-right" data-resize="1" aria-label="Resize image from right; use arrow keys for width"></button></div><figcaption class="image-caption" contenteditable="true" lang="en-GB" spellcheck="true" aria-label="Image caption">${runsHTML(block.caption)}</figcaption><div class="image-controls" aria-label="Image controls"><label>Alt text <input class="image-alt" value="${escapeHTML(block.alt)}" required aria-required="true" aria-describedby="alt-state-${block.id}"></label><span id="alt-state-${block.id}" class="alt-state">${block.alt?'Alt text supplied':'Review required: add alt text'}</span><span class="alignment" role="group" aria-label="Image alignment"><button data-align="left" aria-label="Align image left">Left</button><button data-align="centre" aria-label="Align image centre">Centre</button><button data-align="right" aria-label="Align image right">Right</button></span><button data-remove aria-label="Remove image">Remove</button></div>`;return el}
function cover(){const s=sheet('cover');const m=state.meta;s.insertAdjacentHTML('beforeend',`<div class="cover-kicker">${escapeHTML(m.documentType)} · ${escapeHTML(m.status)}</div><h1>${escapeHTML(m.clientName)}</h1><h2>${escapeHTML(m.projectTitle)} — ${escapeHTML(m.subtitle)}</h2><dl class="meta-grid"><dt>Document</dt><dd>${escapeHTML(m.documentType)}</dd><dt>Date</dt><dd>${escapeHTML(m.date)}</dd><dt>Version</dt><dd>${escapeHTML(m.version)}</dd><dt>Adviser</dt><dd>${escapeHTML(m.adviser)}</dd><dt>Status</dt><dd>${escapeHTML(m.status)}</dd></dl>`);return s}
function toc(pageMap={}){const s=sheet('contents');let entries=state.sections.map(g=>({g,label:g.title,cls:''})).concat(state.steps.map((g,i)=>({g,label:`Step ${i+1}. ${g.title}`,cls:'toc-step'})));s.insertAdjacentHTML('beforeend',`<h1 class="doc-title">Contents</h1><ol class="toc">${entries.map(e=>`<li class="${e.cls} ${hasReview(e.g)?'toc-review':''}"><a href="#anchor-${e.g.id}">${escapeHTML(e.label)}</a><span class="dots"></span><span class="toc-page">${pageMap[`anchor-${e.g.id}`]||'—'}</span></li>`).join('')}</ol>`);return s}
function groupSheet(g,title,kind){const s=sheet(kind);s.id=`anchor-${g.id}`;s.tabIndex=-1;s.insertAdjacentHTML('beforeend',kind==='step'?`<div class="step-label">${escapeHTML(title.split('.')[0])}</div><h1 class="section-title">${escapeHTML(title)}</h1>`:`<h1 class="section-title">${escapeHTML(title)}</h1>`);const body=document.createElement('div');body.className='document-body';g.blocks.forEach(b=>body.append(b.type==='image'?imageBlock(b):editable(b)));s.append(body);return s}
async function render(){const source=document.createElement('main');source.append(cover(),toc(window.__pageMap||{}));state.sections.forEach(g=>source.append(groupSheet(g,g.title,'section')));state.steps.forEach((g,i)=>source.append(groupSheet(g,`Step ${i+1}. ${g.title}`,'step')));const previewer=new Paged.Previewer();const target=$('#preview');await previewer.preview(source,[],target);const pages=[...target.children],map={};pages.forEach((p,i)=>{footer(p.querySelector('.sheet-source'),i+1,pages.length);p.dataset.pageNumber=i+1;p.querySelectorAll('[id^="anchor-"]').forEach(a=>map[a.id]=i+1)});window.__pageMap=map;target.querySelectorAll('.toc-page').forEach((n,i)=>{const keys=[...state.sections,...state.steps].map(g=>`anchor-${g.id}`);n.textContent=map[keys[i]]||'—'});bindEditing();$('#total').textContent=pages.length;currentPage=Math.min(currentPage,pages.length);$('#current').textContent=currentPage}
function findBlock(id){for(const group of [...state.sections,...state.steps]){const b=group.blocks.find(x=>x.id===id);if(b)return b}}
function commit(mutator){const previous=state;state=structuredClone(state);mutator();state=normaliseDocument(state);history.value=previous;history.commit(state);state=history.value;render()}
function bindEditing(){document.querySelectorAll('.editable-block').forEach(el=>{el.addEventListener('focusin',()=>window.activeBlock=el.dataset.blockId);el.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>syncBlock(el),450)});el.addEventListener('paste',plainPaste);el.addEventListener('keydown',listKeys)});document.querySelectorAll('.image-block').forEach(bindImage);document.querySelectorAll('.toc a').forEach(a=>a.onclick=e=>{e.preventDefault();const dest=document.querySelector(a.getAttribute('href'));dest?.closest('.pagedjs_page')?.scrollIntoView({behavior:'smooth',block:'center'});dest?.focus()})}
function plainPaste(e){e.preventDefault();const t=e.clipboardData.getData('text/plain'),sel=getSelection();if(sel.rangeCount){sel.deleteFromDocument();sel.getRangeAt(0).insertNode(document.createTextNode(t));sel.collapseToEnd()}e.currentTarget.dispatchEvent(new InputEvent('input'))}
function syncBlock(el){const id=el.dataset.blockId;commit(()=>{const b=findBlock(id);if(!b)return;if(b.type.endsWith('List'))b.items=[...el.querySelectorAll('.list-item')].map((x,i)=>({id:x.dataset.itemId||`${id}-item-${i}`,level:+x.dataset.level||1,runs:[{text:x.textContent,highlight:false,link:null}]}));else b.runs=[{text:el.textContent,highlight:false,link:null}]})}
function listKeys(e){const el=e.currentTarget;if(!el.dataset.listType)return;const item=e.target.closest('.list-item');if(e.key==='Enter'){e.preventDefault();if(!item.textContent.trim()){commit(()=>{const b=findBlock(el.dataset.blockId);b.type='paragraph';b.runs=[{text:'',highlight:false,link:null}];delete b.items});return}const n=document.createElement('div');n.className='list-item';n.dataset.itemId=`item-${Date.now()}`;n.dataset.level=item.dataset.level;n.style.listStyleType=el.dataset.listType==='numberList'?'decimal':'disc';n.contentEditable='true';item.after(n);n.focus()}if(e.key==='Backspace'&&item&&!item.textContent&&getSelection().anchorOffset===0){e.preventDefault();commit(()=>{const b=findBlock(el.dataset.blockId);b.type='paragraph';b.runs=[{text:'',highlight:false,link:null}];delete b.items})}}
function selectedOffsets(el){const sel=getSelection();if(!sel.rangeCount||!el.contains(sel.anchorNode)||!el.contains(sel.focusNode))return null;const r=sel.getRangeAt(0),pre=document.createRange();pre.selectNodeContents(el);pre.setEnd(r.startContainer,r.startOffset);const start=pre.toString().length;return[start,start+r.toString().length]}
function transformSelection(kind,value){const el=document.querySelector(`[data-block-id="${window.activeBlock}"]`),off=el&&selectedOffsets(el);if(!off||off[0]===off[1])return;commit(()=>{const b=findBlock(window.activeBlock);if(!b||!b.runs)return;const text=textRuns(b.runs),[a,z]=off;b.runs=normaliseRuns([{text:text.slice(0,a)},{text:text.slice(a,z),highlight:kind==='highlight'?!runsAt(b.runs,a).highlight:runsAt(b.runs,a).highlight,link:kind==='link'?{href:value}:kind==='unlink'?null:runsAt(b.runs,a).link},{text:text.slice(z)}])})}
function runsAt(runs,pos){let n=0;return runs.find(r=>(n+=r.text.length)>pos)||runs.at(-1)||{}}
function updateImage(id,change){commit(()=>Object.assign(findBlock(id),change))}
function bindImage(el){const id=el.dataset.blockId;el.addEventListener('focusin',()=>{window.activeBlock=id;el.classList.add('selected')});el.addEventListener('focusout',e=>{if(!el.contains(e.relatedTarget))el.classList.remove('selected')});el.querySelector('.image-caption').addEventListener('paste',plainPaste);el.querySelector('.image-caption').addEventListener('input',e=>{clearTimeout(timer);timer=setTimeout(()=>updateImage(id,{caption:normaliseRuns([{text:e.target.textContent}])}),450)});el.querySelector('.image-alt').addEventListener('change',e=>updateImage(id,{alt:e.target.value}));el.querySelectorAll('[data-align]').forEach(b=>b.onclick=()=>updateImage(id,{alignment:b.dataset.align}));el.querySelector('[data-remove]').onclick=()=>commit(()=>{for(const g of [...state.sections,...state.steps]){const i=g.blocks.findIndex(b=>b.id===id);if(i>=0){g.blocks.splice(i,1);break}}});el.addEventListener('keydown',e=>{if(e.target!==el)return;let change;if(e.shiftKey&&e.key==='ArrowLeft')change={alignment:'left'};else if(e.shiftKey&&e.key==='ArrowRight')change={alignment:'right'};else if(e.shiftKey&&e.key==='ArrowUp')change={alignment:'centre'};else if(e.key==='ArrowLeft'||e.key==='ArrowDown')change={widthPercent:findBlock(id).widthPercent-2};else if(e.key==='ArrowRight'||e.key==='ArrowUp')change={widthPercent:findBlock(id).widthPercent+2};if(change){e.preventDefault();updateImage(id,change)}});el.querySelectorAll('[data-resize]').forEach(handle=>{handle.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const grow=(e.key==='ArrowRight'||e.key==='ArrowUp')?1:-1;updateImage(id,{widthPercent:findBlock(id).widthPercent+grow*(e.shiftKey?10:2)})});handle.addEventListener('pointerdown',e=>{e.preventDefault();const start=e.clientX,startWidth=el.getBoundingClientRect().width,available=el.closest('.document-body').getBoundingClientRect().width,direction=+handle.dataset.resize;handle.setPointerCapture(e.pointerId);const move=x=>{const px=startWidth+(x-start)*direction;el.style.width=`${Math.min(100,Math.max(10,px/available*100))}%`};handle.onpointermove=x=>move(x.clientX);handle.onpointerup=()=>{handle.onpointermove=null;handle.onpointerup=null;updateImage(id,{widthPercent:parseFloat(el.style.width)})}})})}
function sniffImageType(bytes){const b=new Uint8Array(bytes);if(b.length>=8&&b[0]===0x89&&b[1]===0x50&&b[2]===0x4e&&b[3]===0x47&&b[4]===0x0d&&b[5]===0x0a&&b[6]===0x1a&&b[7]===0x0a)return'image/png';if(b.length>=3&&b[0]===0xff&&b[1]===0xd8&&b[2]===0xff)return'image/jpeg';if(b.length>=6&&String.fromCharCode(...b.slice(0,6)).match(/^GIF8[79]a$/))return'image/gif';if(b.length>=12&&String.fromCharCode(...b.slice(0,4))==='RIFF'&&String.fromCharCode(...b.slice(8,12))==='WEBP')return'image/webp';return null}
async function decodeDimensions(file){if('createImageBitmap'in window){try{const bitmap=await createImageBitmap(file);const dimensions={width:bitmap.width,height:bitmap.height};bitmap.close();return dimensions}catch{ /* The Image fallback provides consistent browser coverage. */ }}const url=URL.createObjectURL(file);try{return await new Promise((resolve,reject)=>{const image=new Image;image.onload=()=>resolve({width:image.naturalWidth,height:image.naturalHeight});image.onerror=()=>reject(Error('The image content is malformed or cannot be decoded.'));image.src=url})}finally{URL.revokeObjectURL(url)}}
const fileDataURL=file=>new Promise((resolve,reject)=>{const reader=new FileReader;reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('The image could not be read.'));reader.readAsDataURL(file)});
function imageError(message=''){$('#image-error').textContent=message}
async function insertImage(file){imageError();try{if(!file) return;if(!IMAGE_MIME_TYPES.includes(file.type))throw Error('Unsupported image type. Choose a PNG, JPEG, GIF or WebP file.');if(file.size>MAX_IMAGE_BYTES)throw Error(`Image is too large. The maximum file size is ${MAX_IMAGE_BYTES/1024/1024} MB.`);const bytes=await file.arrayBuffer(),decodedType=sniffImageType(bytes);if(decodedType!==file.type)throw Error('The selected file content does not match its reported image type.');const {width,height}=await decodeDimensions(file);if(!width||!height)throw Error('The image has invalid dimensions.');if(width>MAX_IMAGE_DIMENSION||height>MAX_IMAGE_DIMENSION||width*height>MAX_IMAGE_PIXELS)throw Error(`Image dimensions are too large (maximum ${MAX_IMAGE_DIMENSION} px per side and ${MAX_IMAGE_PIXELS.toLocaleString()} pixels).`);const src=await fileDataURL(file),block={id:`image-${Date.now()}`,type:'image',src,mime:file.type,intrinsicWidth:width,intrinsicHeight:height,widthPercent:60,alignment:'centre',alt:'',caption:[]};commit(()=>{let group=state.sections[0]||state.steps[0];let index=group?.blocks.length||0;for(const g of [...state.sections,...state.steps]){const i=g.blocks.findIndex(b=>b.id===window.activeBlock);if(i>=0){group=g;index=i+1;break}}if(!group)throw Error('There is no document section in which to insert the image.');group.blocks.splice(index,0,block)});window.activeBlock=block.id}catch(error){imageError(error.message)}}
function command(action){const id=window.activeBlock;if(action==='undo'){state=history.undo();return render()}if(action==='redo'){state=history.redo();return render()}if(action==='highlight')return transformSelection('highlight');if(action==='link'){const href=prompt('Link destination (https:, http:, mailto: or #anchor)');if(href&&safeHref(href))transformSelection('link',href);else if(href)alert('That link destination is not permitted.');return}if(action==='unlink')return transformSelection('unlink');if(!id)return;commit(()=>{const b=findBlock(id);if(action.startsWith('heading')){b.type='heading';b.level=+action.at(-1);b.runs=b.runs||b.items?.flatMap(i=>i.runs)||[]}else if(action==='body'){b.type='paragraph';b.runs=b.runs||b.items?.flatMap(i=>i.runs)||[]}else if(['bulletList','numberList'].includes(action)){const runs=b.runs||[{text:'List item'}];b.type=action;b.items=[{id:`${id}-item`,level:1,runs}];delete b.runs}else if(action==='indent'||action==='outdent'){if(b.items)b.items[0].level=Math.max(1,Math.min(3,b.items[0].level+(action==='indent'?1:-1)))}})}
document.querySelectorAll('[data-command]').forEach(x=>x.onclick=()=>command(x.dataset.command));$('#style').onchange=e=>command(e.target.value);$('#insert-image').onclick=()=>{$('#image-file').value='';$('#image-file').click()};$('#image-file').onchange=e=>insertImage(e.target.files[0]);function go(n){const pages=[...document.querySelectorAll('.pagedjs_page')];currentPage=Math.max(1,Math.min(pages.length,n));$('#current').textContent=currentPage;pages[currentPage-1]?.scrollIntoView({behavior:'smooth',block:'center'})}$('#prev').onclick=()=>go(currentPage-1);$('#next').onclick=()=>go(currentPage+1);addEventListener('keydown',e=>{if(e.altKey&&e.key==='ArrowLeft')go(currentPage-1);if(e.altKey&&e.key==='ArrowRight')go(currentPage+1)});render();
