import { seedDocument, normaliseDocument, normaliseRuns, safeHref, safeImageSrc, transactionProposals, hasReview, newId, stableAnchor, METADATA_KEYS } from './state/schema.js';
import { History } from './state/history.js';
import { readDraft, readRecovery, saveDraft, saveVersion, listVersions, deleteVersion, encodeSnapshot, snapshotFromLocation } from './state/persistence.js';
import { runsFromElement, transformRuns, insertPlainText } from './editor/dom-runs.js';
import { validatedLink, confirmStepDeletion, splitListRuns, insertTableRowBeforeTotals, restoreTextSelection } from './editor/interactions.js';
import { RepaginationScheduler } from './editor/repagination.js';

let initial=seedDocument,loadedRevision=0;try{const draft=readDraft();initial=snapshotFromLocation()||draft?.document||readRecovery()?.document||seedDocument;loadedRevision=draft?.revision||0}catch(error){setTimeout(()=>alert(error.message),0)}const history = new History(initial); let state = history.checkout(); let currentPage = 1;let dirty=false,autosaveTimer=null;
export const editorSelection = { activeStepId:null, activeBlockId:null, container:null, row:null, column:null, blockType:null, offsets:null, restoreFocus:false };
const pending = new Map(), pendingStepTitles = new Map(); const $ = s => document.querySelector(s); const esc = x => String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const runText = runs => (runs||[]).map(r=>r.text).join('');
const runsHTML = runs => (runs||[]).map(r=>{let text=esc(r.text).replace(/\n/g,'<br>');if(r.link)text=`<a href="${esc(r.link.href)}">${text}</a>`;return r.highlight?`<mark>${text}</mark>`:text}).join('');
const editableRuns = (runs, attrs='') => `<span class="editable-runs" contenteditable="true" spellcheck="true" ${attrs}>${runsHTML(runs)}</span>`;
const allGroups = () => [...state.sections,...state.steps,...state.appendices];
const findBlock = id => { for(const group of allGroups()){const block=group.blocks.find(x=>x.id===id);if(block)return {group,block};} return {}; };
const selectedStep = () => state.steps.find(x=>x.id===editorSelection.activeStepId);

function header(){const x=document.createElement('header');x.className='page-header';x.innerHTML=`<span class="header-brand">UBTA</span><span class="header-details">${esc(state.meta.clientName)} · ${esc(state.meta.projectTitle)} · ${esc(state.meta.version)}</span>`;return x}
function sheet(kind){const x=document.createElement('section');x.className=`sheet-source ${kind}`;x.append(header());return x}
function footer(x,n,total){const f=document.createElement('footer');f.className='page-footer';f.textContent=`Page ${n} of ${total}`;x.append(f)}
function blockElement(block){const x=document.createElement('div');x.className='editable-block';x.dataset.blockId=block.id;x.dataset.type=block.type;x.dataset.level=block.level||'';x.draggable=false;
  if(['heading','paragraph'].includes(block.type))x.innerHTML=editableRuns(block.runs,'data-container="block"');
  else if(block.type.endsWith('List')){x.classList.add('list-block');x.dataset.listType=block.type;x.innerHTML=block.items.map(i=>`<div class="list-item" contenteditable="true" data-container="item" data-item-id="${i.id}" data-level="${i.level}">${runsHTML(i.runs)}</div>`).join('')}
  else if(block.type==='table'){x.classList.add('table-block');x.innerHTML=`<table><caption>${editableRuns(block.captionRuns,'data-container="caption"')}</caption><colgroup>${block.columns.map(c=>`<col style="width:${c.width}%">`).join('')}</colgroup><thead><tr>${block.columns.map((c,i)=>`<th>${editableRuns(c.headingRuns,`data-container="heading" data-column="${i}"`)}</th>`).join('')}</tr></thead><tbody>${block.rows.map((r,ri)=>`<tr class="${r.isTotal?'total-row':''}" data-row="${ri}">${r.cells.map((c,ci)=>`<td>${editableRuns(c.runs,`data-container="cell" data-row="${ri}" data-column="${ci}"`)}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
  else {x.classList.add('image-block');x.innerHTML=block.src?`<figure><img src="${esc(block.src)}" alt="${esc(block.alt||'')}" style="width:${block.width}%"><figcaption>${editableRuns(block.captionRuns,'data-container="image-caption"')}</figcaption></figure>`:'<p class="image-error">Image unavailable.</p>'}
  x.insertAdjacentHTML('afterbegin','<div class="block-controls" contenteditable="false"><button data-block-move="before" aria-label="Move block before">↑</button><button data-block-move="after" aria-label="Move block after">↓</button></div>');return x
}
function groupSheet(group,title,kind){const x=sheet(kind);x.id=stableAnchor(group);x.tabIndex=-1;if(kind==='step'){x.dataset.stepId=group.id;if(group.id===editorSelection.activeStepId)x.classList.add('is-selected');x.innerHTML+=`<div class="step-heading"><div class="step-label">${esc(title.match(/^Step \d+/)?.[0]||'')}</div><input class="step-title" data-step-title="${group.id}" value="${esc(group.title)}"></div>`}else x.innerHTML+=`<h1 class="section-title">${esc(title)}</h1>`;const body=document.createElement('div');body.className='document-body';group.blocks.forEach(b=>body.append(blockElement(b)));x.append(body);return x}
function cover(){const x=sheet('cover');x.innerHTML+=`<div class="cover-kicker">${esc(state.meta.documentType)} · ${esc(state.meta.status)}</div><h1>${esc(state.meta.clientName)}</h1><h2>${esc(state.meta.projectTitle)}</h2><p>${esc(state.meta.subtitle)}</p><p>${esc(state.meta.date)} · ${esc(state.meta.adviser)} · ${esc(state.meta.version)}</p>`;return x}
function contents(map={}){const x=sheet('contents');const entries=[...state.sections,...state.appendices,...state.steps];x.innerHTML+='<h1 class="doc-title">Contents</h1><ol class="toc">'+entries.map(g=>`<li class="${hasReview(g)?'toc-review':''}"><a href="#${stableAnchor(g)}">${esc(g.title)}</a><span class="dots"></span><span>${map[stableAnchor(g)]||'—'}</span></li>`).join('')+'</ol>';return x}
function captureSelection(){const el=activeEditable();if(!el)return;const s=getSelection();if(!s.rangeCount||!el.contains(s.anchorNode))return;const r=s.getRangeAt(0),before=document.createRange();before.selectNodeContents(el);before.setEnd(r.startContainer,r.startOffset);editorSelection.offsets=[before.toString().length,before.toString().length+r.toString().length]}
function captureView(){captureSelection();return {currentPage,scrollX:window.scrollX,scrollY:window.scrollY,selection:structuredClone(editorSelection)}}
async function restoreView(view){currentPage=Math.max(1,Math.min($('#preview').children.length,view.currentPage));Object.assign(editorSelection,view.selection);$('#current').textContent=currentPage;if(editorSelection.restoreFocus)restoreTextSelection(activeEditable(),editorSelection.offsets);window.scrollTo(view.scrollX,view.scrollY)}
async function paginate({isCurrent}){const source=document.createElement('main'),staging=document.createElement('div');staging.className='pagedjs_pages';source.append(cover(),contents(window.__pageMap||{}));state.sections.forEach(g=>source.append(groupSheet(g,g.title,'section')));state.steps.forEach((g,i)=>source.append(groupSheet(g,`Step ${i+1}. ${g.title}`,'step')));state.appendices.forEach(g=>source.append(groupSheet(g,g.title,'appendix')));await new Paged.Previewer().preview(source,[],staging);if(!isCurrent())return false;const pages=[...staging.children],map={};pages.forEach((p,i)=>{footer(p.querySelector('.sheet-source'),i+1,pages.length);p.querySelectorAll('[id^=anchor-]').forEach(a=>map[a.id]=i+1)});if(!isCurrent())return false;window.__pageMap=map;$('#preview').replaceChildren(...pages);bindEditing();updateControls();$('#total').textContent=pages.length;return true}
const repagination=new RepaginationScheduler(paginate,{capture:captureView,restore:restoreView});
const render=({immediate=true}={})=>repagination.request({immediate});

function activeEditable(){const id=editorSelection.activeBlockId;if(!id)return editorSelection.activeStepId?document.querySelector(`[data-step-title="${editorSelection.activeStepId}"]`):null;const block=document.querySelector(`[data-block-id="${id}"]`);if(!block)return null;const c=editorSelection.container;if(c==='block')return block.querySelector('[data-container=block]');if(c==='item')return block.querySelector(`[data-item-id="${editorSelection.itemId}"]`);if(c==='caption')return block.querySelector('[data-container=caption]');if(c==='image-caption')return block.querySelector('[data-container=image-caption]');if(c==='heading')return block.querySelector(`[data-container=heading][data-column="${editorSelection.column}"]`);if(c==='cell')return block.querySelector(`[data-container=cell][data-row="${editorSelection.row}"][data-column="${editorSelection.column}"]`);return block}
function setActive(target){const step=target.closest('[data-step-id]');if(step)editorSelection.activeStepId=step.dataset.stepId;const block=target.closest('[data-block-id]');editorSelection.activeBlockId=block?.dataset.blockId||null;editorSelection.blockType=block?.dataset.type||null;editorSelection.container=target.dataset.container||(['heading','paragraph'].includes(editorSelection.blockType)?'block':null);editorSelection.itemId=target.dataset.itemId||null;editorSelection.row=target.dataset.row??null;editorSelection.column=target.dataset.column??null;editorSelection.restoreFocus=true;document.querySelectorAll('[data-step-id]').forEach(x=>x.classList.toggle('is-selected',x.dataset.stepId===editorSelection.activeStepId));updateControls()}
function syncElement(el, record=true){if(!el?.isConnected)return false;const blockEl=el.closest('[data-block-id]'), found=findBlock(blockEl?.dataset.blockId);if(!found.block)return false;const before=structuredClone(state);const b=found.block,c=el.dataset.container;if(c==='item'){const i=b.items.find(x=>x.id===el.dataset.itemId);if(i)i.runs=runsFromElement(el)}else if(c==='caption')b.captionRuns=runsFromElement(el);else if(c==='image-caption')b.captionRuns=runsFromElement(el);else if(c==='heading')b.columns[+el.dataset.column].headingRuns=runsFromElement(el);else if(c==='cell')b.rows[+el.dataset.row]?.cells[+el.dataset.column]&&(b.rows[+el.dataset.row].cells[+el.dataset.column].runs=runsFromElement(el));else b.runs=runsFromElement(el);state=normaliseDocument(state);if(record)history.commit(state);else history.replace(state);const changed=JSON.stringify(before)!==JSON.stringify(state);if(changed)markDirty();return changed}
function schedule(el){const key=targetKey(el),old=pending.get(key);if(old)clearTimeout(old.timer);pending.set(key,{el,timer:setTimeout(()=>{const p=pending.get(key);if(!p||p.el!==el||!el.isConnected)return;syncElement(el);pending.delete(key);updateControls();render({immediate:false})},450)})}
const targetKey=el=>[el.closest('[data-block-id]')?.dataset.blockId,el.dataset.container,el.dataset.itemId,el.dataset.row,el.dataset.column].join(':');
function flushTarget(el,record=true){const key=targetKey(el),p=pending.get(key);if(!p)return;clearTimeout(p.timer);pending.delete(key);if(p.el.isConnected)syncElement(p.el,record)}
function syncStepTitle(el,{renderAfter=true}={}){const pendingTitle=pendingStepTitles.get(el.dataset.stepTitle);if(pendingTitle)clearTimeout(pendingTitle.timer);pendingStepTitles.delete(el.dataset.stepTitle);if(!el.isConnected)return false;const step=state.steps.find(x=>x.id===el.dataset.stepTitle),title=el.value.trim()||'Untitled step';if(!step||step.title===title)return false;step.title=title;history.commit(state);markDirty();updateControls();if(renderAfter)render({immediate:false});return true}
function flushAll(record=true){[...pending.values()].forEach(p=>{clearTimeout(p.timer);if(p.el.isConnected)syncElement(p.el,record)});pending.clear();[...pendingStepTitles.values()].forEach(p=>syncStepTitle(p.el,{renderAfter:false}))}
const hasPendingInputs=()=>pending.size>0||pendingStepTitles.size>0;
function markDirty(){dirty=true;const indicator=$('#save-state');if(indicator){indicator.textContent='Unsaved changes';indicator.className='save-state dirty'}clearTimeout(autosaveTimer);autosaveTimer=setTimeout(()=>persistDraft(),1500)}
function commit(mutator,{focus=true}={}){flushAll();const before=structuredClone(state);mutator();state=normaliseDocument(state);history.replace(before);history.commit(state);state=history.checkout();markDirty();editorSelection.restoreFocus=focus;return render({restore:focus})}

function bindEditing(){document.querySelectorAll('[data-step-id]').forEach(x=>x.addEventListener('pointerdown',e=>{if(!e.target.closest('button'))setActive(e.target)}));document.querySelectorAll('[contenteditable=true]').forEach(el=>{el.addEventListener('focusin',()=>setActive(el));el.addEventListener('input',()=>{repagination.cancel();schedule(el)});el.addEventListener('blur',()=>{flushTarget(el);editorSelection.restoreFocus=false});el.addEventListener('paste',e=>insertPlainText(e,document))});
 document.querySelectorAll('.step-title').forEach(el=>{const sync=()=>syncStepTitle(el);el.addEventListener('focusin',()=>setActive(el));el.addEventListener('input',()=>{repagination.cancel();const old=pendingStepTitles.get(el.dataset.stepTitle);if(old)clearTimeout(old.timer);pendingStepTitles.set(el.dataset.stepTitle,{el,timer:setTimeout(sync,450)})});el.addEventListener('blur',()=>{sync();editorSelection.restoreFocus=false});el.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();el.blur()}else if(e.key==='Tab')editorSelection.restoreFocus=false})});
 document.querySelectorAll('.list-item').forEach(el=>el.addEventListener('keydown',listEnter));document.querySelectorAll('[data-container=cell]').forEach(el=>el.addEventListener('keydown',tableTab));document.querySelectorAll('[data-block-move]').forEach(b=>b.onclick=()=>moveBlock(b.closest('[data-block-id]').dataset.blockId,b.dataset.blockMove));document.querySelectorAll('.toc a').forEach(a=>a.onclick=e=>{e.preventDefault();document.querySelector(a.getAttribute('href'))?.focus()})}
function listEnter(e){if(e.key!=='Enter')return;e.preventDefault();const el=e.currentTarget;flushTarget(el);const {block}=findBlock(el.closest('[data-block-id]').dataset.blockId),index=block.items.findIndex(i=>i.id===el.dataset.itemId);const offsets=getOffsets(el),text=runText(block.items[index].runs);if(!text.trim()){commit(()=>{block.items.splice(index,1);if(!block.items.length){block.type='paragraph';block.runs=[];delete block.items}});return}const id=newId('item');commit(()=>{const item=block.items[index],[before,after]=splitListRuns(item.runs,offsets[0]);item.runs=before;block.items.splice(index+1,0,{id,level:item.level,runs:after});editorSelection.itemId=id;editorSelection.offsets=[0,0]})}
function tableTab(e){if(e.key!=='Tab')return;const cells=[...document.querySelectorAll(`[data-block-id="${editorSelection.activeBlockId}"] [data-container=cell]`)],i=cells.indexOf(e.currentTarget);if(e.shiftKey||i<cells.length-1)return;e.preventDefault();flushTarget(e.currentTarget);const {block}=findBlock(editorSelection.activeBlockId);commit(()=>{const insert=insertTableRowBeforeTotals(block,newId);editorSelection.row=insert;editorSelection.column=0;editorSelection.offsets=[0,0]})}
const getOffsets=el=>{const s=getSelection();if(!s.rangeCount)return[0,0];const r=s.getRangeAt(0),b=document.createRange();b.selectNodeContents(el);b.setEnd(r.startContainer,r.startOffset);return[b.toString().length,b.toString().length+r.toString().length]};
function resolveRuns(){const {block}=findBlock(editorSelection.activeBlockId);if(!block)return null;if(editorSelection.container==='block')return block.runs;if(editorSelection.container==='item')return block.items.find(x=>x.id===editorSelection.itemId)?.runs;if(editorSelection.container==='caption'||editorSelection.container==='image-caption')return block.captionRuns;if(editorSelection.container==='heading')return block.columns[editorSelection.column]?.headingRuns;if(editorSelection.container==='cell')return block.rows[editorSelection.row]?.cells[editorSelection.column]?.runs;return null}
function replaceResolved(runs){const {block}=findBlock(editorSelection.activeBlockId);if(editorSelection.container==='block')block.runs=runs;else if(editorSelection.container==='item')block.items.find(x=>x.id===editorSelection.itemId).runs=runs;else if(['caption','image-caption'].includes(editorSelection.container))block.captionRuns=runs;else if(editorSelection.container==='heading')block.columns[editorSelection.column].headingRuns=runs;else if(editorSelection.container==='cell')block.rows[editorSelection.row].cells[editorSelection.column].runs=runs}
function transformSelection(kind,value){flushAll();const el=activeEditable();if(el)editorSelection.offsets=getOffsets(el);const runs=resolveRuns();if(!runs)return;if(kind==='highlight'&&editorSelection.offsets?.[0]===editorSelection.offsets?.[1])editorSelection.offsets=[0,runText(runs).length];commit(()=>replaceResolved(transformRuns(runs,editorSelection.offsets,kind,value)))}
function insertBlock(type){const step=selectedStep();if(!step)return;const active=step.blocks.findIndex(x=>x.id===editorSelection.activeBlockId),index=active<0?step.blocks.length:active+1,id=newId('block');let block={id,type,runs:[]};if(type.endsWith('List'))block={id,type,items:[{id:newId('item'),level:1,runs:[]}]};if(type==='table')block={id,type,captionRuns:[{text:'Table caption'}],columns:[{id:newId('column'),headingRuns:[{text:'Column 1'}],width:50},{id:newId('column'),headingRuns:[{text:'Column 2'}],width:50}],rows:[{id:newId('row'),cells:[{id:newId('cell'),runs:[]},{id:newId('cell'),runs:[]}]}]};commit(()=>{step.blocks.splice(index,0,block);editorSelection.activeBlockId=id;editorSelection.blockType=type;editorSelection.container=type==='table'?'cell':type.endsWith('List')?'item':'block';editorSelection.row=0;editorSelection.column=0;editorSelection.itemId=block.items?.[0]?.id;editorSelection.offsets=[0,0]})}
function moveBlock(id,direction){const {group}=findBlock(id);if(!group)return;const i=group.blocks.findIndex(x=>x.id===id),j=direction==='before'?i-1:i+1;if(j<0||j>=group.blocks.length)return;commit(()=>{[group.blocks[i],group.blocks[j]]=[group.blocks[j],group.blocks[i]];editorSelection.activeBlockId=id;announce(`Block moved to position ${j+1}`)})}
function manageStep(action){flushAll();const index=state.steps.findIndex(x=>x.id===editorSelection.activeStepId);if(index<0)return;if(action==='deleteStep'){if(!confirmStepDeletion(state.steps,index,confirm))return;return commit(()=>{state.steps.splice(index,1);editorSelection.activeStepId=state.steps[Math.min(index,state.steps.length-1)]?.id||null;editorSelection.activeBlockId=null;announce('Step deleted')})}const target=index+(action==='moveStepUp'?-1:1);if(target<0||target>=state.steps.length)return;commit(()=>{[state.steps[index],state.steps[target]]=[state.steps[target],state.steps[index]];announce(`Step moved to position ${target+1}`)})}
function addStep(where='after'){const index=state.steps.findIndex(x=>x.id===editorSelection.activeStepId);if(index<0)return;const id=newId('step'),blockId=newId('block'),at=index+(where==='after'?1:0);commit(()=>{state.steps.splice(at,0,{id,title:'New transaction step',blocks:[{id:blockId,type:'paragraph',runs:[]}]});editorSelection.activeStepId=id;editorSelection.activeBlockId=blockId;editorSelection.container='block';editorSelection.blockType='paragraph';editorSelection.offsets=[0,0]})}
function tableMutation(action){const {block}=findBlock(editorSelection.activeBlockId);if(block?.type!=='table')return;if(action==='addRow')commit(()=>{const at=block.rows.findIndex(r=>r.isTotal);block.rows.splice(at<0?block.rows.length:at,0,{id:newId('row'),cells:block.columns.map(()=>({id:newId('cell'),runs:[]}))})});if(action==='addColumn')commit(()=>{block.columns.push({id:newId('column'),headingRuns:[{text:`Column ${block.columns.length+1}`}],width:100/(block.columns.length+1)});block.rows.forEach(r=>r.cells.push({id:newId('cell'),runs:[]}))}) ;if(action==='removeRow'&&block.rows.length)commit(()=>block.rows.splice(Math.max(0,+editorSelection.row),1));if(action==='removeColumn'&&block.columns.length>1)commit(()=>{const i=Math.max(0,+editorSelection.column);block.columns.splice(i,1);block.rows.forEach(r=>r.cells.splice(i,1))})}
function linkPicker(){captureSelection();const dialog=$('#link-picker'),list=$('#link-destination');list.innerHTML=[...state.steps,...state.appendices].map(x=>`<option value="#${stableAnchor(x)}">${esc(x.title||'Untitled')}</option>`).join('');dialog.showModal()}
function addImage(){if(!selectedStep())return;const form=$('#image-form'),error=$('#image-form-error');form.reset();error.hidden=true;error.textContent='';$('#image-dialog').showModal();form.elements.src.focus()}
function command(action){flushAll();if(action==='undo'||action==='redo'){pending.forEach(x=>clearTimeout(x.timer));pending.clear();state=action==='undo'?history.undo():history.redo();markDirty();if(!state.steps.some(x=>x.id===editorSelection.activeStepId))editorSelection.activeStepId=state.steps[0]?.id||null;return render()}if(action==='addStepBefore'||action==='addStepAfter')return addStep(action.endsWith('After')?'after':'before');if(['moveStepUp','moveStepDown','deleteStep'].includes(action))return manageStep(action);if(action.startsWith('add')&&action!=='addImage')return insertBlock({addParagraph:'paragraph',addHeading:'heading',addBulletList:'bulletList',addNumberList:'numberList',addTable:'table'}[action]);if(action==='addImage')return addImage();if(['addRow','removeRow','addColumn','removeColumn'].includes(action))return tableMutation(action);if(action==='highlight'||action==='unlink')return transformSelection(action==='unlink'?'unlink':'highlight');if(action==='link')return linkPicker();if(editorSelection.blockType==='image')return;const {block}=findBlock(editorSelection.activeBlockId);if(!block||!['heading','paragraph','bulletList','numberList'].includes(block.type))return;if(action.startsWith('heading')||action==='body'||['bulletList','numberList'].includes(action))commit(()=>{if(action.startsWith('heading')){block.type='heading';block.level=+action.at(-1);block.runs=block.runs||block.items?.flatMap(i=>i.runs)||[]}else if(action==='body'){block.type='paragraph';block.runs=block.runs||block.items?.flatMap(i=>i.runs)||[]}else{block.items=block.items||[{id:newId('item'),level:1,runs:block.runs||[]}];block.type=action;delete block.runs}})}
function announce(message){$('#editor-status').textContent='';requestAnimationFrame(()=>$('#editor-status').textContent=message)}
function updateControls(){const i=state.steps.findIndex(x=>x.id===editorSelection.activeStepId),step=i>=0;document.querySelectorAll('[data-command=moveStepUp]').forEach(x=>x.disabled=!step||i===0);document.querySelectorAll('[data-command=moveStepDown]').forEach(x=>x.disabled=!step||i===state.steps.length-1);document.querySelectorAll('[data-command=deleteStep]').forEach(x=>x.disabled=!step||state.steps.length===1);document.querySelectorAll('[data-requires-step]').forEach(x=>x.disabled=!step);const runs=resolveRuns(),text=!!runs;document.querySelectorAll('[data-text-command]').forEach(x=>x.disabled=!text);const {block}=findBlock(editorSelection.activeBlockId),style=$('#style');document.querySelectorAll('[data-table-command]').forEach(x=>x.hidden=block?.type!=='table');style.disabled=!text;if(block?.type==='heading')style.value=`heading${block.level}`;else if(block?.type==='paragraph')style.value='body'}
document.querySelectorAll('[data-command]').forEach(b=>{b.addEventListener('pointerdown',e=>{if(b.dataset.textCommand!==undefined){e.preventDefault();captureSelection()}});b.addEventListener('click',()=>command(b.dataset.command))});$('#style').onchange=e=>command(e.target.value);$('#link-form').onsubmit=e=>{e.preventDefault();const external=$('#external-link').value,href=validatedLink(external,$('#link-destination').value);if(href){$('#link-picker').close();transformSelection('link',href)}else alert('Enter a valid HTTPS, HTTP, mailto, or internal destination.')};
function persistDraft({quiet=false}={}){flushAll(false);clearTimeout(autosaveTimer);let result;try{result=saveDraft(state,loadedRevision)}catch(error){const indicator=$('#save-state');indicator.textContent='Save failed';indicator.className='save-state error';if(!quiet)alert(`Could not save this draft: ${error.message}`);return false}if(!result.ok){const indicator=$('#save-state');indicator.textContent='Newer draft in another tab';indicator.className='save-state error';if(!quiet)alert('This draft was changed in another tab. Reload before saving so that the newer draft and recovery copy are not overwritten.');return false}loadedRevision=result.revision;dirty=false;const indicator=$('#save-state');indicator.textContent=`Saved locally ${new Date(result.record.savedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`;indicator.className='save-state';return true}
function versionsDialog(){const dialog=$('#versions-dialog'),list=$('#versions-list'),versions=listVersions();list.innerHTML=versions.length?versions.map(v=>`<div class="version-row"><span><b>${esc(v.label)}</b><small>${new Date(v.savedAt).toLocaleString()}</small></span><button type="button" data-restore-version="${esc(v.id)}">Restore</button><button type="button" data-delete-version="${esc(v.id)}">Delete</button></div>`).join(''):'<p>No saved versions yet.</p>';list.querySelectorAll('[data-restore-version]').forEach(button=>button.onclick=async()=>{const version=listVersions().find(v=>v.id===button.dataset.restoreVersion);if(!version)return;if(!persistDraft())return;state=normaliseDocument(version.document);history.commit(state);markDirty();dialog.close();await render({restore:false});announce('Saved version restored')});list.querySelectorAll('[data-delete-version]').forEach(button=>button.onclick=()=>{deleteVersion(button.dataset.deleteVersion);versionsDialog()});if(!dialog.open)dialog.showModal()}
const propertiesDialog=$('#properties-dialog'),propertiesForm=$('#properties-form');$('#document-properties').onclick=()=>{for(const key of METADATA_KEYS)propertiesForm.elements[key].value=state.meta[key];propertiesDialog.showModal()};propertiesForm.querySelector('[data-close-properties]').onclick=()=>propertiesDialog.close();propertiesForm.onsubmit=async event=>{event.preventDefault();for(const key of METADATA_KEYS)propertiesForm.elements[key].value=propertiesForm.elements[key].value.trim();if(!propertiesForm.reportValidity())return;await commit(()=>{for(const key of METADATA_KEYS)state.meta[key]=propertiesForm.elements[key].value},{focus:false});propertiesDialog.close();announce('Document properties updated')};
const imageDialog=$('#image-dialog'),imageForm=$('#image-form'),imageError=$('#image-form-error');imageForm.querySelector('[data-close-image]').onclick=()=>imageDialog.close();imageForm.onsubmit=event=>{event.preventDefault();const src=imageForm.elements.src.value.trim(),alt=imageForm.elements.alt.value.trim(),caption=imageForm.elements.caption.value.trim(),widthValue=imageForm.elements.width.value;if(!src||!alt||!imageForm.checkValidity()){imageError.textContent='Enter an image URL and alternative text, and use a width between 20 and 100.';imageError.hidden=false;return}let parsed;try{parsed=new URL(src)}catch{imageError.textContent='Enter a complete, well-formed image URL.';imageError.hidden=false;return}if(parsed.protocol!=='https:'){imageError.textContent='Unsupported protocol. Image URLs must use HTTPS.';imageError.hidden=false;return}if(!/\.(png|jpe?g|gif|webp)$/i.test(parsed.pathname)){imageError.textContent='Unsupported image extension. Use a PNG, JPEG, GIF or WebP URL.';imageError.hidden=false;return}const publishedSrc=safeImageSrc(src);if(!publishedSrc){imageError.textContent='Enter a valid public HTTPS image URL.';imageError.hidden=false;return}const step=selectedStep(),id=newId('image'),at=Math.max(0,step.blocks.findIndex(x=>x.id===editorSelection.activeBlockId)+1),width=widthValue===''?100:Number(widthValue);commit(()=>{step.blocks.splice(at,0,{id,type:'image',src:publishedSrc,alt,captionRuns:caption?[{text:caption}]:[],width});editorSelection.activeBlockId=id;editorSelection.blockType='image';editorSelection.container=null});imageDialog.close();announce('Published image added')};
$('#save-draft').onclick=()=>persistDraft();$('#save-version').onclick=()=>{if(!persistDraft())return;const label=prompt('Name this saved version:',`${state.meta.version||'Version'} — ${state.meta.status||'Draft'}`);if(label===null)return;saveVersion(state,label);announce('Named version saved')};$('#show-versions').onclick=versionsDialog;$('#share-snapshot').onclick=async()=>{flushAll(false);const url=`${location.href.split('#')[0]}#snapshot=${encodeSnapshot(state)}`;try{await navigator.clipboard.writeText(url);announce('Snapshot link copied')}catch{prompt('Copy this validated snapshot link:',url)}};
addEventListener('pagehide',()=>{if(dirty||hasPendingInputs())persistDraft({quiet:true})});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'&&(dirty||hasPendingInputs()))persistDraft({quiet:true})});addEventListener('storage',event=>{if(event.key==='ubta:draft'&&readDraft()?.revision!==loadedRevision){const indicator=$('#save-state');indicator.textContent='Newer draft in another tab';indicator.className='save-state error'}});
function go(page){const pages=[...document.querySelectorAll('.pagedjs_page')];currentPage=Math.max(1,Math.min(pages.length,page));$('#current').textContent=currentPage;pages[currentPage-1]?.scrollIntoView({behavior:'smooth',block:'center'})}$('#prev').onclick=()=>go(currentPage-1);$('#next').onclick=()=>go(currentPage+1);render({restore:false});
